fixtures:
  repositories:
    archive:
      repo: "https://github.com/voxpupuli/puppet-archive"
      ref: "v3.2.0"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "https://github.com/camptocamp/puppet-systemd.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
  symlinks:
    znapzend: "#{source_dir}"
