fixtures:
  repositories:
    archive:
      repo: "https://github.com/voxpupuli/puppet-archive"
      ref: "v3.2.0"
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    znapzend: "#{source_dir}"
