---

.gitignore:
  required:
    - '/.vscode/'

.gitlab-ci.yml:
  delete: true

.rubocop.yml:
  selected_profile: off

.travis.yml:
  unmanaged: true

appveyor.yml:
  selete: true

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
    ':system_tests':
      - gem: beaker
      - gem: beaker-module_install_helper
      - gem: beaker-puppet_install_helper
      - gem: beaker-rspec
      - gem: beaker-vagrant
      - gem: deep_merge
      - gem: serverspec

Rakefile:
  default_disabled_lint_checks:
    - '140chars'

spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
