---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - bundle show puppet
  - bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
    - rvm: 2.1.9
      bundler_args: --without system_tests development
      env: PUPPET_VERSION="~> 4.7.0" CHECK=test
    - rvm: 2.1.9
      bundler_args: --without system_tests development
      env: PUPPET_VERSION="~> 4.10.0" CHECK=test
    - rvm: 2.4.4
      bundler_args: --without system_tests development
      env: PUPPET_VERSION="~> 5.0" CHECK=test
    - rvm: 2.4.4
      bundler_args: --without development
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/centos-6 CHECK=beaker
      services: docker
      sudo: required
    - rvm: 2.4.4
      bundler_args: --without development
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/centos-7 CHECK=beaker
      services: docker
      sudo: required
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
