HOSTS:
  centos-7-x64:
    roles:
      - master
    platform: el-7-x86_64
    box: centos/7
    box_url: https://app.vagrantup.com/centos/boxes/7
    box_version: ">=1804"
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type: foss
  vagrant_memsize: 4096
